### ISSUE TITLE
Use `nanflag` in `mean()` and `std()` to Remove Dependence in Statistics Toolbox

### ISSUE THREAD

**Issue by RoyiAvital** [raacampbell/notBoxPlot#3]
Hello,

Could you please switch from using [`nanmean()`](https://www.mathworks.com/help/stats/nanmean.html) and [`nanstd()`](https://www.mathworks.com/help/stats/nanstd.html) to [`mean()`](https://www.mathworks.com/help/matlab/ref/mean.html) and [`std()`](https://www.mathworks.com/help/matlab/ref/std.html) and use the `nanflag`?
This will result in independence from the [Statistics and Machine Learning Toolbox](https://www.mathworks.com/products/statistics/).

Thank You.

**Comment by raacampbell** [comment]
d7fcd27280e51dcb0871298969edb311d8bf5f1a  should do what you want. 
I also simplified the install procedure, but that means you'll need to update your path when you pull. You just need to add the `code` directory now.

**Comment by RoyiAvital** [comment]
Lovely,

Thank You.
